[package]
name = "testing"
version = "0.8.4"
authors = ["Martin Geisler <martin@geisler.net>"]
edition = "2018"
descripton = "something"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
