name: Create release pull request

on:
  create:
    branches:
      - 'release-*'

#  repository_dispatch:
#    types: make-release

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - run: |
          echo "${{ toJson(github) }}"

      - run: |
          echo "::set-env name=VERSION::$(echo ${{ github.ref }} | cut -d '-' -f 2-)"
          echo "::set-env name=NAME::$(grep '^name =' Cargo.toml | cut -d '"' -f 2)"

      - id: vars
        run: |
          echo "::set-output name=version::$VERSION"
          echo "::set-output name=$NAME"

      - name: Verify version
        run: |
          echo "$VERSION" | grep -q '^[0-9]\+\.[0-9]\+\.[0-9]\+$'

      - name: Configure Git user
        run: |
          git config user.name "Martin Geisler"
          git config user.email "martin@geisler.net"

      - name: Add version number and date to changelog
        run: |
          if grep -q '## Unreleased' README.md; then
            sed -i -e "s/## Unreleased/## Version $VERSION ($(date -I))/" README.md
          else
            sed -i -e "/# Changelog/a\\\\n## Version $VERSION ($(date -I))" README.md
          fi
          git commit --all -m "Update changelog for version $VERSION"

#      - run: |
#          cargo install comrak
#          comrak --width 70 --gfm --to commonmark README.md > README.md.tmp
#          mv README.md.tmp README.md

      - run: |
          .github/workflows/update-toml "$NAME" "$VERSION" README.md

      - run: |
          .github/workflows/update-html-root-url "$NAME" "$VERSION" src/*.rs

      - name: Update crate version
        uses: thomaseizinger/set-crate-version@1.0.0
        with:
          version: ${{ steps.vars.outputs.version }}

      - run: |
          git commit --all -m "Bump version to $VERSION"

      - run: git push origin

      - uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: 'release-${{ steps.vars.outputs.version }}',
              base: 'master',
              title: 'Release ${{ steps.vars.outputs.version }}',
              body: 'New release',
              draft: true,
            })
