name: Publish new release

on:
  pull_request:
    types:
      - edited
    branches:
      - 'release-*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - run: |
          echo "${{ toJson(github) }}"

      - run: |
          cargo publish --dry-run
