name: Publish new release

on:
  pull_request:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - ready_for_review
      - locked
      - unlocked
      - review_requested
      - review_request_removed

#    types:
#      - ready_for_review
#    branches:
#      - 'release-*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - id: set-version
        run: |
          echo "::set-env name=VERSION::$(echo ${{ github.ref }} | cut -d - -f 2-)"
          echo "::set-output name=version::$(echo ${{ github.ref }} | cut -d - -f 2-)"

      - name: Configure Git
        run: |
          git config user.name "Martin Geisler"
          git config user.email "martin@geisler.net"

      - run: |
          echo "${{ toJson(github.event.action) }}"

      - run: |
          echo "${{ toJson(github.event) }}"

      - run: |
          echo "${{ toJson(github) }}"

      - run: |
          cargo publish --dry-run

      - run: |
          git tag ${{ steps.set-version.outputs.version }}

      - name: Add "Unreleased" section
        run: |
          sed -i -e '/# Changelog/a\\n## Unreleased' README.md

      - run: |
          git add README.md

      - run: |
          git commit -m "Prepare for next release"

      - run: git log

      - run: |
          git push --follow-tags origin
