name: Publish a new release

on:
  pull_request

#  repository_dispatch:
#    types: make-release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - run: echo "${{ toJson(github) }}"

      - id: find-version
        run: |
          echo "::set-env name=VERSION::$(echo ${{ github.head_ref }} | cut -d - -f 2-)"

      - run: |
          echo "Version: $VERSION"

#      - name: Configure Git
#        run: |
#          git config user.email "martin@geisler.net"
#          git config user.name "Martin Geisler"
#
#      - name: Show version
#        run: |
#          echo "$(date -I): ${{ github.event.client_payload.version }}"
#
#      - run: |
#            git checkout -b release-${{ github.event.client_payload.version }}
#
#      - name: Update version number
#        run: |
#          sed -i -e "s/## Unreleased/## $(date -I): Version ${{ github.event.client_payload.version }}/" README.md
#
#        run: git diff
#
#      - run: |
#          git add README.md
#
#      - run: |
#          git commit -m "Preparing version ${{ github.event.client_payload.version }}"
#
#      - run: git log
#
#      - run: git push origin release-${{ github.event.client_payload.version }}
