name: Publish a new release

on:
  repository_dispatch:
    types: make-release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Show version
        run: |
          echo "$(date -I): ${{ github.event.client_payload.version }}"

      - name: Create release-${{ github.event.client_payload.version }} branch
        uses: peterjgrainger/action-create-branch@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: release-${{ github.event.client_payload.version }}

      - name: Update version number
        run: |
          sed -i -e "s/## Unreleased/## $(date -I): Version ${{ github.event.client_payload.version }}/" README.md

      - name: Diff
        run: git diff

      - uses: EndBug/add-and-commit@v4
        with:
          add: README.md
          author_name: Martin A Geisler
          author_email: martin+auto@geisler.net
          message: 'Your commit message'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: git log
