name: Publish a new release

on:
  repository_dispatch:
    types: make-release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.email "martin@geisler.net
          git config --global user.name "Martin Geisler"

      - name: Show version
        run: |
          echo "$(date -I): ${{ github.event.client_payload.version }}"

      - run: |
            git branch release-${{ github.event.client_payload.version }}

      - name: Update version number
        run: |
          sed -i -e "s/## Unreleased/## $(date -I): Version ${{ github.event.client_payload.version }}/" README.md

      - name: Diff
        run: git diff

      - run: |
          git add README.md
          git commit -m "Preparing version ${{ github.event.client_payload.version }}"

      - run: git log

      - run: git push origin release-${{ github.event.client_payload.version }}
