name: Publish a new release

on:
  repository_dispatch:
    types: make-release

jobs:
  print-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$(date -I): ${{ github.event.client_payload.version }}"
